import boto3
import json
import pandas as pd
from datetime import datetime
from ib_insync import *

# ---- CONFIG ----
DATA_BUCKET = "jgs3-automation-data"
REPORTS_BUCKET = "jgs3-automation-reports"
LOGS_BUCKET = "jgs3-automation-logs"
TODAY = datetime.now().strftime('%Y/%m/%d')

s3 = boto3.client('s3')
ses = boto3.client('ses', region_name='us-east-1')
EMAIL = "jefftgibbs@gmail.com"

def log_to_s3(message, level="INFO"):
    entry = {
        "timestamp": datetime.now().isoformat(),
        "level": level,
        "source": "ibkr_pipeline",
        "message": message
    }
    log_key = f"pipeline_logs/{TODAY}/run_{datetime.now().strftime('%H%M%S')}.json"
    s3.put_object(
        Bucket=LOGS_BUCKET,
        Key=log_key,
        Body=json.dumps(entry, indent=2),
        ContentType='application/json'
    )
    print(f"[{level}] {message}")

def fetch_ibkr_data(ib):
    """Pull real account data from IBKR."""
    summary = ib.accountSummary()
    account_data = {}
    for item in summary:
        if item.tag in ['NetLiquidation', 'TotalCashValue', 'UnrealizedPnL',
                        'RealizedPnL', 'BuyingPower', 'GrossPositionValue']:
            account_data[item.tag] = float(item.value)

    positions = ib.positions()
    position_rows = []
    for pos in positions:
        contract = pos.contract
        position_rows.append({
            'symbol': contract.symbol,
            'sec_type': contract.secType,
            'shares': float(pos.position),
            'avg_cost': round(pos.avgCost, 2),
            'market_value': round(float(pos.position) * pos.avgCost, 2)
        })

    return account_data, pd.DataFrame(position_rows) if position_rows else pd.DataFrame()

def generate_report(account_data, positions_df):
    """Build HTML report from real IBKR data."""
    nlv = account_data.get('NetLiquidation', 0)
    cash = account_data.get('TotalCashValue', 0)
    unrealized = account_data.get('UnrealizedPnL', 0)
    realized = account_data.get('RealizedPnL', 0)

    green = '#28a745'
    red = '#dc3545'

    positions_html = ""
    if not positions_df.empty:
        for _, row in positions_df.iterrows():
            positions_html += f"""
            <tr>
                <td style="padding:8px;border-bottom:1px solid #eee"><b>{row['symbol']}</b></td>
                <td style="padding:8px;border-bottom:1px solid #eee">{row['sec_type']}</td>
                <td style="padding:8px;border-bottom:1px solid #eee">{row['shares']:.0f}</td>
                <td style="padding:8px;border-bottom:1px solid #eee">${row['avg_cost']:,.2f}</td>
                <td style="padding:8px;border-bottom:1px solid #eee">${row['market_value']:,.2f}</td>
            </tr>"""
    else:
        positions_html = '<tr><td colspan="5" style="padding:8px;color:#999">No open positions</td></tr>'

    pnl_color = green if unrealized >= 0 else red

    html = f"""
    <html><body style="font-family:Arial,sans-serif;max-width:700px;margin:auto">
    <h2 style="color:#1B3A5C">IBKR Daily Portfolio Report</h2>
    <p style="color:#666">{datetime.now().strftime('%A, %B %d, %Y %I:%M %p')}</p>
    <p style="color:#999;font-size:12px">Account: DU7726760 (Paper Trading)</p>

    <div style="background:#f8f9fa;padding:20px;border-radius:8px;margin:20px 0">
        <h3 style="margin-top:0">Account Summary</h3>
        <p>Net Liquidation: <b>${nlv:,.2f}</b></p>
        <p>Cash: <b>${cash:,.2f}</b></p>
        <p>Unrealized P&L: <b style="color:{pnl_color}">${unrealized:+,.2f}</b></p>
        <p>Realized P&L: <b>${realized:+,.2f}</b></p>
    </div>

    <table style="width:100%;border-collapse:collapse">
        <tr style="background:#1B3A5C;color:white">
            <th style="padding:10px;text-align:left">Symbol</th>
            <th style="padding:10px;text-align:left">Type</th>
            <th style="padding:10px;text-align:left">Shares</th>
            <th style="padding:10px;text-align:left">Avg Cost</th>
            <th style="padding:10px;text-align:left">Value</th>
        </tr>
        {positions_html}
    </table>

    <p style="color:#999;font-size:12px;margin-top:30px">
        Generated by IBKR Automation Pipeline on EC2
    </p>
    </body></html>
    """
    return html

def run_pipeline():
    ib = IB()
    try:
        log_to_s3("IBKR pipeline started")

        # Step 1: Connect
        ib.connect('127.0.0.1', 4002, clientId=10, timeout=30)
        log_to_s3(f"Connected to IBKR — Account: {ib.managedAccounts()}")

        # Step 2: Fetch real data
        account_data, positions_df = fetch_ibkr_data(ib)
        log_to_s3(f"Fetched account data: NLV=${account_data.get('NetLiquidation', 0):,.2f}")

        # Step 3: Upload raw data
        account_key = f"ibkr/account/{TODAY}/summary.json"
        s3.put_object(
            Bucket=DATA_BUCKET,
            Key=account_key,
            Body=json.dumps({**account_data, 'timestamp': datetime.now().isoformat()}),
            ContentType='application/json'
        )
        log_to_s3(f"Account data uploaded to s3://{DATA_BUCKET}/{account_key}")

        if not positions_df.empty:
            pos_key = f"ibkr/positions/{TODAY}/positions.csv"
            csv_path = "/tmp/positions.csv"
            positions_df.to_csv(csv_path, index=False)
            s3.upload_file(csv_path, DATA_BUCKET, pos_key)
            log_to_s3(f"Positions uploaded to s3://{DATA_BUCKET}/{pos_key}")
        else:
            log_to_s3("No positions to upload")

        # Step 4: Generate and upload report
        html_report = generate_report(account_data, positions_df)
        report_key = f"ibkr/daily_reports/{TODAY}/portfolio_report.html"
        s3.put_object(
            Bucket=REPORTS_BUCKET,
            Key=report_key,
            Body=html_report,
            ContentType='text/html'
        )
        log_to_s3(f"Report uploaded to s3://{REPORTS_BUCKET}/{report_key}")

        # Step 5: Console summary
        print("\n" + "=" * 50)
        print("  IBKR PORTFOLIO SUMMARY (LIVE DATA)")
        print("=" * 50)
        for key, val in account_data.items():
            print(f"  {key}: ${val:>12,.2f}")
        if not positions_df.empty:
            print(f"\n{positions_df.to_string(index=False)}")
        else:
            print("\n  No open positions")
        print(f"\n{'=' * 50}")

        # Step 6: Email the report
        try:
            ses.send_email(
                Source=EMAIL,
                Destination={'ToAddresses': [EMAIL]},
                Message={
                    'Subject': {
                        'Data': f"IBKR Daily Report — {datetime.now().strftime('%b %d, %Y')}",
                        'Charset': 'UTF-8'
                    },
                    'Body': {
                        'Html': {
                            'Data': html_report,
                            'Charset': 'UTF-8'
                        }
                    }
                }
            )
            log_to_s3("Email sent successfully")
        except Exception as e:
            log_to_s3(f"Email failed: {str(e)}", level="ERROR")
        log_to_s3("IBKR pipeline completed successfully")

    except Exception as e:
        log_to_s3(f"Pipeline FAILED: {str(e)}", level="ERROR")
        raise
    finally:
        if ib.isConnected():
            ib.disconnect()

if __name__ == '__main__':
    run_pipeline()
